### ISSUE TITLE
Issue:  Vagueness in  steps for building tailtracer

### ISSUE THREAD

**Issue by darint00** [rquedas/otel4devs#2]
We are planning on building a receiver for our product and I'm going through this tutorial.  Best tutorial I've found.  But I ran into a snag and I'm not sure how to get help.  I'm at the following section:

Adding the receiver factory to the Collector's initialization

I went ahead and updated the code manually (components.go) as described adding the import and the tailtrace to the factory.Recivers.

The instructions say this:
Collector with dev-otelcol command should look like after building it with the current codebase:

And it shows the output of running dev-otelcol --config config.yaml

If I rebuild the dev-otelcol with ocb it essentially regenerates the components.go and the code I put in place as mentioned above is gone.  Is there a different way this needs to be built, or a different way to add this code.  IE in builder-config.yaml and let ocb generate it accordingly?

**Comment by rquedas** [comment]
Hi @darint00!
I am glad you found the tutorial helpful, we tried to make it that way. :)

ocb assumes that all your component modules are ready for consumption (no further development) and it fully generates the code to support the build of a new collector based on those component definitions.

By building the current codebase, I meant:

dev-otelcol % cd dev-otelcol
dev-otelcol % go build

**Comment by darint00** [comment]
This issue is closed.
